### ISSUE TITLE
[HLA_Study.py::ERROR]: Failed to perform logistic regression test on the Binary Markers

### ISSUE THREAD

**Issue by isabelle-boothman** [WansonChoi/HATK#14]
Hi when I run HATK after running CookHLA, I get this error: 
[HLA_Study.py::ERROR]: Failed to perform logistic regression test on the Binary Markers

This is the CookHLA code I ran: 
$ python CookHLA.py \
    -i severe_cADR_chr6_repheno_plink_updatedsex \
    -hg 19 \
    -o HLA_T1DGC_CookHLA \
    -ref T1DGC/T1DGC_REF \
    -mem 2g \
    # -mp 2   # The number of available cores for Multiprocessing.
    # -bgl4   # If you want to use Beagle4 instead of Beagle5.

This is the code HATK code I ran:
python3 HATK.py \
    --variants severe_cADR_chr6_repheno_plink_updatedsex.COPY.LiftDown_hg18 \
    --hped HLA_T1DGC_CookHLA.MHC.HLA_IMPUTATION_OUT.hped \
    --2field \
    --pheno cases_controls_rephenotype.pheno \
    --pheno-name ALL \
    --out HLA.hatk \
    --imgt 3320 \
    --hg 19 \
    --imgt-dir example/IMGTHLA3320 \
    --multiprocess 

I'm sure what caused the error, just wondering if anyone knew how to fix it? Thanks

**Comment by WansonChoi** [comment]
@isabelle-boothman 

Hi, thank you for your error report.

Currently, I take care of HATK's maintenance. Could you share the cause?

**Comment by isabelle-boothman** [comment]
Hi,

Thanks for your reply.

I am not sure what caused the error.
I ran CookHLA first using this code:
$ python CookHLA.py \
    -i
/space3/ssr_extra_analysis_space/repheno_plink_files/severe_cADR_epipgx_cpnds_chr6_repheno_plink_updatedsex
\
    -hg 19 \
    -o
/space3/ssr_extra_analysis_space/CookHLA_2021/Epipgx_cpnds_HLA_T1DGC_CookHLA
\
    -ref /usr/local/src/SNP2HLA_package_v1.0.2/T1DGC/T1DGC_REF \
    -mem 2g \
    # -mp 2   # The number of available cores for Multiprocessing.
    # -bgl4   # If you want to use Beagle4 instead of Beagle5.


and then I ran HATK using this code:

python3 HATK.py \
    --variants
/space3/ssr_extra_analysis_space/CookHLA_2021/severe_cADR_epipgx_cpnds_chr6_repheno_plink_updatedsex.COPY.LiftDown_hg18
\
    --hped
/space3/ssr_extra_analysis_space/CookHLA_2021/Epipgx_cpnds_HLA_T1DGC_CookHLA.MHC.HLA_IMPUTATION_OUT.hped
\
    --2field \
    --pheno
/space3/ssr_extra_analysis_space/repheno_plink_files/EpiPGX_CPNDS_cases_controls_rephenotype.pheno
\
    --pheno-name ALL \
    --out
/space3/ssr_extra_analysis_space/CookHLA_2021/HATK/Epipgx_cpnds_HLA.hatk \
    --imgt 3320 \
    --hg 19 \
    --imgt-dir example/IMGTHLA3320 \
    --multiprocess 2

and got this error:
[HLA_Study.py::ERROR]: Failed to perform logistic regression test on the
Binary
Markers('/space3/ssr_extra_analysis_space/CookHLA_2021/HATK/Epipgx_cpnds_HLA.hatk').

Thanks for all your help.

Best wishes,
Isabelle

**Comment by WansonChoi** [comment]
@isabelle-boothman 

I'm sorry, I misunderstood that you found out the cause because you wrote "I'm sure what caused the error, ...".

To investigate the cause, Can you share

(1) the input genotype data('severe_cADR_chr6_repheno_plink_updatedsex.COPY.LiftDown_hg18.{bed,bim,fam}),
(2) the imputed hped file('HLA_T1DGC_CookHLA.MHC.HLA_IMPUTATION_OUT.hped'), and
(3) the phenotype data('cases_controls_rephenotype.pheno')

if they aren't related to privacy/security issues? (Maybe you can anonymize the sample labels.)

Then, I can investigate the cause more closely. It's hard for me to pinpoint the exact cause only with your argument usages and the error message.

If you can't, then please share the HATK main log file and all intermediate PLINK log files generated in the process.

**Comment by isabelle-boothman** [comment]
Hi,

So sorry for the delay, but I actually got it working the problem was I had
coded my controls as 0 and cases as 1 but they needed to be coded as
controls = 1, cases =2,

Thanks again,
Isabelle

**Comment by WansonChoi** [comment]
@isabelle-boothman 

Nice! The encoding was the cause and you found it yourself. Maybe I should add a function to check the encoding of a given phenotype file.

Thanks again for your error report and I am closing this issue.
